version: "3"
services:
  kafka-cluster:
    container_name: kafka-cluster
    image: landoop/fast-data-dev:2.2
    environment:
      ADV_HOST: 192.168.0.100         # Change to 192.168.0.100 if using Docker Toolbox
      RUNTESTS: 0                     # Disable Running tests so the cluster starts faster
      FORWARDLOGS: 0                  # Disable running 5 file source connectors that bring application logs
      SAMPLEDATA: 0                   # Do no create sea_vessel_position_reports, nyc_yellow_taxi_trip_data
    ports:
      - 2181:2181                     # Zookeeper
      - 3030:3030                     # Landoop UI
      - 8081-8083:8081-8083           # REST Proxy, Schema Registry, Kafka Connect ports
      - 9581-9585:9581-9585           # JMX Ports
      - 9092:9092                     # Kafka Broker