server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ashimjk/spring-cloud-git-config-tolls
          # username: ashim
          # password: ashim
          search-paths:
            - 'station*'
          repos:
            perf:
              pattern:
                - '*/perf'
              uri: https://github.com/ashimjk/spring-cloud-git-config-perfs
              search-paths:
                - 'station*'
